project_id = "hlfozjnlhahdbnosltxl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[functions.scrape-rentop]
verify_jwt = false

[functions.test-voice]
verify_jwt = false

[functions.validate-user]
verify_jwt = false